- NumPy 

NumPy is a foundational package for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. NumPy's core data structure is the ndarray, which allows for efficient storage and manipulation of large datasets.

- Matrix Multiplication and Dot Product

Q1. Given two matrices, perform matrix multiplication and compute the dot product of two vectors.

In [ ]:
import numpy as np

# Matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Vectors
v1 = np.array([1, 2])
v2 = np.array([3, 4])

# Matrix multiplication
C = np.dot(A, B)
print("Matrix Multiplication:\n", C)
# [[19 22]
#  [43 50]]

# Dot product of vectors
dot_product = np.dot(v1, v2)
print("Dot Product:", dot_product)
# 11

- Eigenvalues and Eigenvectors

Q2. Compute the eigenvalues and eigenvectors of a given square matrix.

In [ ]:
import numpy as np

# Matrix
A = np.array([[3, 1], [2, 4]])

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
# [4.61803399 2.38196601]
print("Eigenvectors:\n", eigenvectors)
# [[ 0.52573111 -0.85065081]
#  [ 0.85065081  0.52573111]]

- Singular Value Decomposition (SVD)

Q3. Perform singular value decomposition on a given matrix.

In [ ]:
import numpy as np

# Matrix
A = np.array([[1, 2], [3, 4], [5, 6]])

# Singular Value Decomposition
U, S, VT = np.linalg.svd(A)
print("U matrix:\n", U)
print("Singular values:", S)
print("VT matrix:\n", VT)

- Solving a System of Linear Equations

Solve the system of linear equations given by Ax = b.

In [ ]:
import numpy as np

# Coefficient matrix
A = np.array([[3, 1], [1, 2]])

# Dependent variable values
b = np.array([9, 8])

# Solve for x
x = np.linalg.solve(A, b)
print("Solution for x:", x)
# [2. 3.]

- Broadcasting and Element-wise Operations

Q5. Given a matrix, add a vector to each row of the matrix using broadcasting.

In [ ]:
import numpy as np

# Matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Vector
v = np.array([1, 0, 1])

# Broadcasting addition
B = A + v
print("Matrix after broadcasting addition:\n", B)
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]]

- Generating Random Samples

Q6. Generate a 3x3 matrix of random samples from a standard normal distribution.

In [ ]:
import numpy as np

# Seed for reproducibility
np.random.seed(0)

# Random samples from standard normal distribution
random_matrix = np.random.randn(3, 3)
print("Random matrix:\n", random_matrix)
# [[ 1.76405235  0.40015721  0.97873798]
#  [ 2.2408932   1.86755799 -0.97727788]
#  [ 0.95008842 -0.15135721 -0.10321885]]

- Custom Universal Function (ufunc)

Q7. Create a custom universal function that computes the cube of each element in an array.

In [ ]:
import numpy as np

# Define the function
def cube(x):
    return x ** 3

# Create a custom ufunc
cube_ufunc = np.frompyfunc(cube, 1, 1)

# Array
arr = np.array([1, 2, 3, 4])

# Apply custom ufunc
cubed_arr = cube_ufunc(arr)
print("Cubed array:", cubed_arr)
# [1 8 27 64]

- Fancy Indexing

Q8.  Use fancy indexing to select elements from an array that meet specific conditions.

In [ ]:
import numpy as np

# Array
arr = np.array([10, 20, 30, 40, 50])

# Indices of elements greater than 25
indices = np.where(arr > 25)
print("Indices of elements > 25:", indices)
# (array([2, 3, 4]),)

# Elements greater than 25
elements = arr[indices]
print("Elements > 25:", elements)
# [30 40 50]

- Boolean Masking

Q9. Use boolean masking to filter an array.

In [ ]:
import numpy as np

# Array
arr = np.array([10, 15, 20, 25, 30])

# Boolean mask for elements greater than 20
mask = arr > 20
print("Boolean mask:", mask)
# [False False False  True  True]

# Filtered array
filtered_arr = arr[mask]
print("Filtered array:", filtered_arr)
# [25 30]

- Aggregation Functions

Q10. Compute the mean, standard deviation, and sum of elements in an array.

In [ ]:
import numpy as np

# Array
arr = np.array([1, 2, 3, 4, 5])

# Mean
mean = np.mean(arr)
print("Mean:", mean)
# 3.0

# Standard deviation
std_dev = np.std(arr)
print("Standard Deviation:", std_dev)
# 1.4142135623730951

# Sum
sum_arr = np.sum(arr)
print("Sum:", sum_arr)
# 15