Introduction to NumPy:-

NumPy is a powerful library for numerical computing in Python. It provides support for arrays, which are multi-dimensional containers of items of the same type. It offers various functions to perform operations on these arrays efficiently.

1. Applying a Function Element-wise

Q1: Apply a custom function element-wise to a NumPy array without using loops.

In [ ]:
import numpy as np

# Define the function
def square_and_add(x):
    return x**2 + 10

# Array
arr = np.array([1, 2, 3, 4])

# Apply the function element-wise
result = np.vectorize(square_and_add)(arr)
print("Result:", result)
# [11 14 19 26]

2. Outer Product of Vectors

Q2: Compute the outer product of two vectors.

In [ ]:
import numpy as np

# Vectors
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Outer product
outer_product = np.outer(v1, v2)
print("Outer Product:\n", outer_product)
# [[ 4  5  6]
#  [ 8 10 12]
#  [12 15 18]]

3. Diagonal and Trace of a Matrix

Q3: Extract the diagonal of a matrix and compute its trace.

In [ ]:
import numpy as np

# Matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Diagonal
diagonal = np.diag(A)
print("Diagonal:", diagonal)
# [1 5 9]

# Trace
trace = np.trace(A)
print("Trace:", trace)
# 15

4. Compute the Inverse of a Matrix

Q4: Compute the inverse of a given square matrix.

In [ ]:
import numpy as np

# Matrix
A = np.array([[1, 2], [3, 4]])

# Inverse
inverse = np.linalg.inv(A)
print("Inverse:\n", inverse)
# [[-2.   1. ]
#  [ 1.5 -0.5]]

5. Finding the Determinant of a Matrix

Q5: Compute the determinant of a given square matrix.

In [ ]:
import numpy as np

# Matrix
A = np.array([[1, 2], [3, 4]])

# Determinant
determinant = np.linalg.det(A)
print("Determinant:", determinant)
# -2.0000000000000004

6. Generating a Random Permutation

Q6: Generate a random permutation of a given array.

In [ ]:
import numpy as np

# Array
arr = np.array([1, 2, 3, 4, 5])

# Random permutation
permuted_arr = np.random.permutation(arr)
print("Random Permutation:", permuted_arr)

7. Polynomial Fitting

Q7: Fit a polynomial of a specified degree to a set of data points.

In [ ]:
import numpy as np

# Data points
x = np.array([0, 1, 2, 3, 4, 5])
y = np.array([2, 3, 5, 7, 11, 13])

# Polynomial fitting
degree = 2
coefficients = np.polyfit(x, y, degree)
print("Polynomial Coefficients:", coefficients)
# Polynomial coefficients will vary depending on the data points

8. Creating a Toeplitz Matrix

Q8: Create a Toeplitz matrix (constant diagonals) given a vector.

In [ ]:
import numpy as np
from scipy.linalg import toeplitz

# Vector
c = np.array([1, 2, 3, 4])

# Toeplitz matrix
toeplitz_matrix = toeplitz(c)
print("Toeplitz Matrix:\n", toeplitz_matrix)
# [[1 2 3 4]
#  [2 1 2 3]
#  [3 2 1 2]
#  [4 3 2 1]]

9. Rolling Window View

Q9: Create a rolling window view of a 1D array with a specified window size.

In [ ]:
import numpy as np

# Array
arr = np.array([1, 2, 3, 4, 5, 6])

# Rolling window function
def rolling_window(a, window):
    shape = a.shape[:-1] + (a.shape[-1] - window + 1, window)
    strides = a.strides + (a.strides[-1],)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)

# Rolling window view
window_size = 3
rolled_view = rolling_window(arr, window_size)
print("Rolled View:\n", rolled_view)
# [[1 2 3]
#  [2 3 4]
#  [3 4 5]
#  [4 5 6]]

10. Masking and Filtering with Conditions

Q10: Given a 2D array, filter rows where the sum of elements is greater than a specified value.

In [ ]:
import numpy as np

# 2D Array
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Condition: Sum of elements greater than 15
condition = np.sum(A, axis=1) > 15
filtered_rows = A[condition]
print("Filtered Rows:\n", filtered_rows)
# [[ 7  8  9]
#  [10 11 12]]